
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/taskflowxdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE CONFIGURATION
# 'update' automatically creates or updates the DB schema on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SERVER CONFIGURATION
# Port the application will run on (Matches the docker-compose port 8081)
server.port=8081
server.error.include-message=always