apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  # The key is admin.password
  # The value is the Base64 encoded bcrypt hash
  admin.password: PCQyeSQwNSR0U3VkWEw1R09jdmtNMVhOcEZab2RlQnp4LmRFMGI4RGVWYzFQYi5GMlF5RjZaZHFUOGMuUz4=