apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  # The key is admin.password
  # The value is the Base64 encoded bcrypt hash
  admin.password: $2y$05$1kmUxw/VBGlPDAzLjR9rSO8KTcCP/mR1v8CdukKgTgntyADVQSp7m
  admin.passwordMtime: "2026-05-13T10:30:00Z"