apiVersion: v1
kind: Secret
metadata:
  name: argocd-initial-admin-secret
  namespace: argocd
type: Opaque
data:
  # The key is admin.password
  # The value is the Base64 encoded version of the password 
  admin.password: YWRtaW4xMjM=