apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: Taskflowx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: shourya24/auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/taskflowxdb
            - name: ALGORITHM
              value: HS256
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: SECRET_KEY
      restartPolicy: Always