apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: shourya24/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecurepassword123@postgres-db:5432/taskflowxdb
            - name: AUTH_ALGORITHM
              value: HS256
            - name: AUTH_TOKEN_EXPIRE_MINUTES
              value: '30'
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: SECRET_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always