apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: Taskflowx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: taskflowxdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecurepassword123
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 