apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  # Base64 encoded values for the secret data
  AUTH_SERVICE_URL: "http://auth-service:8080"
  TASK_SERVICE_URL: "http://task-service:8081"