apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-deployment
  namespace: Taskflowx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: task-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/taskflowxdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-service-secret
                  key: DATASOURCE_PASSWORD
      restartPolicy: Always